producthunt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products import views

urlpatterns = [
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('admin/', admin.site.urls),
    path('', views.ProductList.as_view(), name='home'),
    path('', include('social_django.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create', views.ProductCreate.as_view(), name='create_product'),
    path('<int:pk>', views.ProductDetail.as_view(), name='detail'),
    path('<int:pk>/add-comment', views.AddComment.as_view(), name='add_comment'),
    path('<int:pk>/update', views.ProductUpdate.as_view(), name='update'),
    path('<int:pk>/delete', views.ProductDelete.as_view(), name='delete'),
    path('upvote/<int:product_id>', views.ProductUpvote.as_view(), name='upvote'),
]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ShopView.as_view(), name='good-list'),
    path('card', views.CardListView.as_view(), name='card'),
    path('card/add/<int:good_id>', views.add_good_to_card, name='add-good-to-card'),
]

products/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse

class Product(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    pub_date = models.DateTimeField(default=timezone.now)
    votes = models.ManyToManyField(User)
    image = models.ImageField(upload_to='images/products/')
    icon = models.ImageField(upload_to='images/products/icons/')
    body = models.TextField()
    hunter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

    def summery(self):
        return self.body[:100] + '...'

    def pub_date_pretty(self):
        return self.pub_date.strftime("%d %B %Y")

    class Meta:
        ordering = ('-pub_date',)

class CommentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(parent=None)

class Comment(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey("self", on_delete=models.CASCADE, related_name='childrens', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    receiver = models.ForeignKey(User, on_delete=None, related_name='recived_comments', blank=True, null=True)
    content = models.TextField('Комментарий')
    pub_date = models.DateTimeField('Дата комментария', default=timezone.now)

    objects = models.Manager() # The default manager.
    first_level = CommentManager() # Get all comments without parents.

    class Meta:
        ordering = ('pub_date',)

    def __str__(self):
        return self.content[0:200]

    @property
    def get_col_length(self):
        if self.parent is not None:
            return 10
        return 12

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFit

class Good(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.PositiveIntegerField()

    image = ProcessedImageField(upload_to='images/goods/',
                                   processors=[ResizeToFit(209, 119)],
                                   format='JPEG',
                                   options={'quality': 100})
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFit(60, 40)],
                                      format='JPEG',
                                      options={'quality': 100})

    def __str__(self):
        return self.name

class Card(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cards')
    good = models.ForeignKey(Good, on_delete=models.CASCADE, related_name='cards')
    quantity = models.PositiveIntegerField()

products/forms.py
from django import forms
from .models import Comment

# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ('title', 'body', 'url', 'icon', 'image')
#         widgets = {
#             'title':forms.TextInput(attrs={'class': 'form-control'}),
#             'body': forms.Textarea(attrs={'class': 'form-control', 'rows':5}),
#             'url': forms.URLInput(attrs={'class': 'form-control'}),
#             'icon': forms.ClearableFileInput(attrs={'class': 'form-control'}),
#             'image': forms.ClearableFileInput(attrs={'class': 'form-control'})
#         }

class CommentForm(forms.Form):
    parent_comment = forms.IntegerField(required=False, widget=forms.HiddenInput())
    receiver = forms.IntegerField(required=False, widget=forms.HiddenInput())
    comment_area = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control mb-2', 'rows':3}))

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.utils.decorators import method_decorator
from .models import Product, Comment
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.contrib.auth.models import User
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from producthunt.decorators import timeit, user_is_product_hunter
from .forms import CommentForm

@method_decorator(timeit, name='dispatch')
class ProductList(ListView):
    model = Product

@method_decorator(login_required(login_url='/accounts/login'), name='dispatch')
class ProductCreate(CreateView):
    model = Product
    fields = ('title', 'body', 'url', 'icon', 'image')

    def form_valid(self, form):
        form.instance.hunter = self.request.user
        form.instance.save()
        return super().form_valid(form)


@method_decorator(login_required(login_url='/accounts/login'), name='dispatch')
class ProductDetail(DetailView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if self.request.user.is_authenticated:
            context['form'] = CommentForm
            context['comments'] = Comment.first_level.filter(product=kwargs['object'].id).order_by('-pub_date')
        return context

@method_decorator(require_http_methods(["POST"]), name='dispatch')
class AddComment(View):
    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        product = get_object_or_404(Product, pk=kwargs.get('pk'))

        if form.is_valid():
            comment = Comment()
            comment.product = product
            comment.author = request.user
            comment.content = form.cleaned_data['comment_area']
            if form.cleaned_data['parent_comment'] is not None:
                comment.parent = get_object_or_404(Comment, pk=form.cleaned_data['parent_comment'])
                comment.receiver = get_object_or_404(User, pk=form.cleaned_data['receiver'])
            comment.save()
        return redirect(product.get_absolute_url())


@method_decorator(login_required(login_url='/accounts/login'), name='dispatch')
@method_decorator(user_is_product_hunter, name='dispatch')
class ProductUpdate(UpdateView):
    model = Product
    template_name_suffix = '_update'
    fields = ('title', 'body', 'url', 'icon', 'image')

@method_decorator(login_required(login_url='/accounts/login'), name='dispatch')
@method_decorator(user_is_product_hunter, name='dispatch')
class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('home')

@method_decorator(login_required(login_url='/accounts/login'), name='dispatch')
@method_decorator(require_http_methods(["POST"]), name='dispatch')
class ProductUpvote(View):
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs['product_id'])
        if product.votes.filter(pk=request.user.id).exists():
            product.votes.remove(request.user)
        else:
            product.votes.add(request.user)
        return redirect(product.get_absolute_url())

products/templates/products/card.html
{% extends 'base.html' %}

{% block content %}
  <h3>Product Card</h3>
  <div class="row">
    <div class="col-md-3 text-center">
      Title
    </div>
    <div class="col-md-3">
      Price
    </div>
    <div class="col-md-3">
      Quantity
    </div>
    <div class="col-md-3">
      Sum
    </div>
  </div>
  <hr>
  <div class="row">
  {% for good in card_list %}
    <div class="col-md-3">
      <img src="{{ good.good.image_thumbnail.url }}" width="50">
      {{ good.good.name }}
    </div>
    <div class="col-md-3">
      {{ good.good.price }}$
    </div>
    <div class="col-md-3">
      {{ good.quantity }}
    </div>
    <div class="col-md-3">
      {% widthratio good.good.price 1 good.quantity %}$
    </div>
  {% endfor %}
  </div>
  <hr>
  <div class="row">
    <div class="col-md-3">
      Total Price
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-3">
      {{ total_price }}$
    </div>
  </div>
{% endblock %}

products/templates/products/create.html
{% extends 'base.html' %}

{% block content %}
  <h3>Create Product</h3>
  <br>

  <form method="POST" action="{% url 'create_product' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-md-6">

      {% include 'form_snippet.html' %}
      <button type="submit" class="btn btn-primary mb-2">Create</button>
      
    </div>
  </form>

{% endblock %}

products/templates/products/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h3>This is Home Page</h3>
  <img src="{% static 'logo2.jpg' %}" class="d-inline-block alighn-top" width="100">
  <hr>

  {% for product in products %}
    <div class="row pt-3">
      <div class="col-md-2">
        <img src="{{ product.icon.url }}" class="img-fluid" onclick="window.location='{% url 'detail' product.id %}';" style="cursor: pointer;">
      </div>
      <div class="col-md-7" onclick="window.location='{% url 'detail' product.id %}';" style="cursor: pointer;">
        {{ product.title }}
        {{ product.body|truncatewords:20|linebreaks }}
      </div>
      <div class="col-md-3">
        <a href="javascript:{document.getElementById('upvote{{ product.id }}').submit()}"><button type="button" class="btn btn-block" name="button">Upvote {{ product.votes.count }}</button></a>
      </div>
    </div>

    <form id="upvote{{ product.id }}" method="POST" action="{% url 'upvote' product.id %}">
      {% csrf_token %}
      <input type="hidden">
    </form>
  {% endfor %}

{% endblock %}

products/templates/products/product_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ product }}"?</p>
    <img src="{{ product.icon.url }}" width="100">
    <input type="submit" class="btn btn-danger" value="Confirm" />
</form>

{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <br>
  <img src="{{ product.icon.url }}" width="100" alt="">
  {{ product.title }}
  <br>
  <br>
  <div class="row">
    <div class="col-md-8">
      <img src="{{ product.image.url }}" class="img-fluid">
      <span class="float-left">Hunted by <strong>{{ product.hunter }}</strong></span>
      <span class="float-right"><strong>{{ product.pub_date_pretty }}</strong> </span>
    </div>
    <div class="col-md-4">
      <a href="javascript:{document.getElementById('upvote').submit()}"><button type="button" class="btn btn-block {% if user in product.votes.all %} btn-success {% endif %}" name="button">Upvote {{ product.votes.count }}</button></a>
    </div>
  </div>
  {{ product.body|linebreaks }}
  <a href="{{ product.url }}">{{ product.url }}</a>

  <form id="upvote" method="POST" action="{% url 'upvote' product.id %}">
    {% csrf_token %}
    <input type="hidden">
  </form>

  {% if product.hunter == user %}
    <a href="{% url 'update' product.id %}" class="btn btn-info">Update</a>
    <a href="{% url 'delete' product.id %}" class="btn btn-danger">Delete</a>
  {% endif %}

  {% if form %}
      <h3 id="write_comment" style="cursor: pointer;"><a onclick="return show_comments_form('write_comment')">Написать комментарий</a></h3>
      <form id="comment_form" action="{% url 'add_comment' product.id %}" method="post" class="mb-3">
      {% csrf_token %}
      {{ form }}
          <button type="submit" class="btn btn-primary">&nbsp;&nbsp;Комментировать</button>
      </form>
  {% else %}
      <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title">Комментарии</h3>
          </div>
          <div class="panel-body">
              Только авторизованные пользователи могут оставлять комментарии.<br />
          </div>
      </div>
  {% endif %}
  <h3>Всего комментариев {{ product.comments.count }}</h3>
  {% for comment in comments %}
        <a name="comment-{{ comment.id }}"></a>
        <div class="row" id="{{ comment.id }}">
            <div class="col-md-{{ comment.get_col_length }} mx-auto">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{% url 'profile' comment.author.id %}" style="text-decoration: none">
                          <img src="{{ comment.author.profile.avatar_url }}" width="30" height="30" class="rounded-circle">
                          <strong>{{ comment.author.username }}</strong>
                        </a>&nbsp;&nbsp;
                        <small class="text-muted">{{ comment.pub_date|timesince }}</small>
                    </div>
                    <div class="panel-body">
                        <div>{{ comment.content|safe }}</div>
                        {% if form %}
                          <a class="btn btn-default btn-xs pull-right"
                            onclick="return show_comments_form({{ comment.id }}, {{ comment.id }}, {{ comment.author.id }})">
                            &nbsp;&nbsp;<small class="text-muted">Ответить</small></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% if comment.is_parent %}
          {% for child in comment.childrens.all %}
            <a name="comment-{{ child.id }}"></a>
            <div class="row" id="{{ child.id }}">
                <div class="col-md-{{ child.get_col_length }} mx-auto">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a href="{% url 'profile' child.author.id %}" style="text-decoration: none">
                              <img src="{{ child.author.profile.avatar_url }}" width="30" height="30" class="rounded-circle">
                            <strong>{{ child.author.username }}</strong>
                            </a>&nbsp;&nbsp;&rarr;&nbsp;&nbsp;
                            {% if child.receiver %}
                              <a href="{% url 'profile' child.receiver.id %}" style="text-decoration: none">
                                <img src="{{ child.receiver.profile.avatar_url }}" width="30" height="30" class="rounded-circle">
                                <strong>{{ child.receiver.username }}</strong>
                              </a>
                            {% endif %}
                            <small class="text-muted">{{ child.pub_date|timesince }}</small>
                        </div>
                        <div class="panel-body">
                            <div>{{ child.content|safe }}</div>
                            {% if form %}
                              <a class="btn btn-default btn-xs pull-right"
                              onclick="return show_comments_form({{ child.id }}, {{ child.parent.id }}, {{ child.author.id }}, 2)">
                              &nbsp;&nbsp;<small class="text-muted">Ответить</small></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
          {% endfor %}
        {% endif %}
    {% endfor %}

  <script type="text/javascript">

    function show_comments_form(comment_id, parent_id=null, receiver=null, level=1)
    {
      if (comment_id == 'write_comment')
      {
          $("#comment_form").removeClass("col-md-10 mx-auto");
          $("#id_parent_comment").val('');
          $("#id_receiver").val('');
      }
      else
      {
          if (level == 1)
          {
            $("#comment_form").removeClass("col-md-10 mx-auto");
            $("#id_parent_comment").val(parent_id);
            $("#id_receiver").val(receiver);
          }
          else
          {
            $("#comment_form").addClass("col-md-10 mx-auto");
            $("#id_parent_comment").val(parent_id);
            $("#id_receiver").val(receiver);
          }
      }
      $("#comment_form").insertAfter("#" + comment_id);

    }
  </script>

{% endblock %}

products/templates/products/product_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h3>Create Product</h3>
  <br>

  <form method="POST" action="{% url 'create_product' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-md-6">
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary mb-2">Create</button>
    </div>
  </form>

{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h3>This is Home Page</h3>
  <img src="{% static 'logo2.jpg' %}" class="d-inline-block alighn-top" width="100">
  <hr>

  {% for product in product_list %}
    <div class="row pt-3">
      <div class="col-md-2">
        <img src="{{ product.icon.url }}" class="img-fluid" onclick="window.location='{{ product.get_absolute_url }}';" style="cursor: pointer;">
      </div>
      <div class="col-md-7" onclick="window.location='{% url 'detail' product.id %}';" style="cursor: pointer;">
        {{ product.title }}
        {{ product.body|truncatewords:20|linebreaks }}
      </div>
      <div class="col-md-3">
        <a href="javascript:{document.getElementById('upvote{{ product.id }}').submit()}"><button type="button" class="btn btn-block {% if user in product.votes.all %} btn-success {% endif %}" name="button">Upvote {{ product.votes.count }}</button></a>
      </div>
    </div>

    <form id="upvote{{ product.id }}" method="POST" action="{% url 'upvote' product.id %}">
      {% csrf_token %}
      <input type="hidden">
    </form>
  {% endfor %}

{% endblock %}

products/templates/products/product_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h3>Update Product</h3>
  <br>

  <form method="POST" action="{% url 'update' product.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-md-6">
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary mb-2">Update</button>
    </div>
  </form>

{% endblock %}